### ISSUE TITLE
Size of hud buttons should adapt to device

### ISSUE THREAD

**Issue by agateau** [agateau/tinywheels#8]
On a 7" tablet, the buttons are too small.

**Comment by gabooh** [comment]
And even smaller on a nexus 9. Left / right seams alright, but I often miss fire/backward.

**Comment by agateau** [comment]
In the mean time you can manually adjust button sizes through the debug screen (look for Hud, Button Size).

**Comment by agateau** [comment]
Button size is now always 2cm, independently of the device size and resolution. Hippie this is good.
